# Generated by Django 4.0.3 on 2022-06-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_forgot_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forgot_password_token',
        ),
    ]
